### ISSUE TITLE
Several issues with highlighting rules

### ISSUE THREAD

**Issue by hillu** [binjo/yara-mode#3]
- In multi-line C-style comments (`/* … */`) only the first line is properly highlighted.
- Single line C++-style comments (`// … EOL`) are not recognized.
- `rule identifier {` highlights "identifier" and everything after it with `font-lock-warning-face` (why this choice anyway?)
- hex strings and regular expressions (strings section) are not recognized.

**Comment by binjo** [comment]
These are indeed bugs and in my todo list for a long time. :/
I'm kinda lazy for "it works", will try fix when I free...PR is mostly welcome. :D

Thanks and cheers.

**Comment by hillu** [comment]
Alright, thanks for the quick answer. I'll see if I can get those issues fixed.

**Comment by binjo** [comment]
ooops, referencing in commit would auto close the issue...
can you please try this update? C-style comment highlight should be fixed, `yara-comment-dwim' should be working too.

**Comment by hillu** [comment]
Yeah, C and C++ style comments are now displayed correctly.
